### PR TITLE
Fix ISE in StartSyncReceiver

### LINKED ISSUE #570: IllegalStateException in StartSyncReceiver
```

java.lang.RuntimeException: 
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3259)
  at android.app.ActivityThread.-wrap17 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1677)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6541)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)
Caused by: java.lang.IllegalStateException: 
  at android.app.ContextImpl.startServiceCommon (ContextImpl.java:1505)
  at android.app.ContextImpl.startService (ContextImpl.java:1461)
  at android.content.ContextWrapper.startService (ContextWrapper.java:644)
  at android.content.ContextWrapper.startService (ContextWrapper.java:644)
  at de.tum.in.tumcampusapp.services.StartSyncReceiver.onReceive (StartSyncReceiver.java:56)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3252)
```

### PR DESCRIPTION
**Pull request by anselm92**
Due to behavior changes in android oreo, services are no longer allowed
to run in the background without the application being in the foreground.
Change all on boot services from IntentService to JobIntentService which enqueues the service work on android oreo devices. See corresponding issue for more information.

Fixes #570

### CODE REVIEW

File: app/src/main/java/de/tum/in/tumcampusapp/services/JobIdConstants.java [hunk 1]
```diff
@@ -0,0 +1,16 @@
+package de.tum.in.tumcampusapp.services;
+
+/**
+ * Created by ansel on 11/11/2017.
+ */
```
Comment (pfent) [inline app/src/main/java/de/tum/in/tumcampusapp/services/JobIdConstants.java]: Please don't commit the autogenerated comments. A small description of the class would be awesome 👍

File: app/src/main/java/de/tum/in/tumcampusapp/services/JobIdConstants.java [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+
+final class JobIdConstants {
```
Comment (kordianbruck) [inline app/src/main/java/de/tum/in/tumcampusapp/services/JobIdConstants.java]: Sorry, I wasn't too clear on this. I meant this class: https://github.com/TCA-Team/TumCampusApp/blob/master/app/src/main/java/de/tum/in/tumcampusapp/auxiliary/Const.kt

Just put any new constants there.
