### PR TITLE
Fix CME when opening the app and cards load

### LINKED ISSUE #631: CME when loading cards
## Steps to Reproduce

1. Open the app (current master)
2. A ConcurrentModificationException is thrown 

## Expected Result

App opens

## Actual Result

App closes unexpected 

## Problem

```
21 23:50:27.826 8508-8548/de.tum.in.tumcampus E/AndroidRuntime: FATAL EXCEPTION: Thread-4
                                                                   Process: de.tum.in.tumcampus, PID: 8508
                                                                   java.util.ConcurrentModificationException
                                                                       at java.util.ArrayList.sort(ArrayList.java:1472)
                                                                       at java.util.Collections.sort(Collections.java:201)
                                                                       at java.util.Collections.sort(Collections.java:156)
                                                                       at de.tum.in.tumcampusapp.managers.CardManager.addCard(CardManager.java:62)
                                                                       at de.tum.in.tumcampusapp.cards.generic.Card.apply(Card.java:158)
                                                                       at de.tum.in.tumcampusapp.cards.generic.NotificationAwareCard.apply(NotificationAwareCard.java:88)
                                                                       at de.tum.in.tumcampusapp.managers.NewsManager.onRequestCard(NewsManager.java:198)
                                                                       at de.tum.in.tumcampusapp.managers.CardManager.update(CardManager.java:138)
                                                                       at de.tum.in.tumcampusapp.services.DownloadService.download(DownloadService.java:145)
                                                                       at de.tum.in.tumcampusapp.services.DownloadService.lambda$onHandleWork$0$DownloadService(DownloadService.java:198)
                                                                       at de.tum.in.tumcampusapp.services.DownloadService$$Lambda$0.run(Unknown Source:4)
                                                                       at java.lang.Thread.run(Thread.java:764)
```

## Suggested Enhancement :sparkles:

Make access to cards list synchronized, to prevent cme's when being updated from various threads

### Environment
* Phone: 
* OS version: 
* TUM Campus App version: 7eabe2d
* Language:

### PR DESCRIPTION
**Pull request by anselm92**
- Since the download services updates the card ui
and the newly added sorting feature sorts the cards
a ConcurrentModification excpetion was thrown

Fixes #631

## Issue

This fixes the following issue(s): #631

### CODE REVIEW

**Comment by pfent** [comment]
Wouldn't we need to synchronize **all** accesses to `newCards` to fix this proper?

File: app/src/main/java/de/tum/in/tumcampusapp/managers/CardManager.java [hunk 1]
```diff
@@ -56,10 +56,10 @@ public static void addCard(Card card) {
         if (card.getPosition() == -1) {
             card.setPosition(newCards.size());
         }
-
-        newCards.add(card);
-
-        Collections.sort(newCards);
+        synchronized (newCards) {
+            newCards.add(card);
+            Collections.sort(newCards);
```
Comment (pfent) [inline app/src/main/java/de/tum/in/tumcampusapp/managers/CardManager.java]: Ok, forget what I wrote.

Please don't sort the list every time a new card is added, but only once in the end.

Comment (anselm92) [reply app/src/main/java/de/tum/in/tumcampusapp/managers/CardManager.java]: Well that's the thing, I can't, because the cafeteria card is added asynchronously now and we never  know when a card's going to be added or how many there'll be in the end.

Comment (pfent) [reply app/src/main/java/de/tum/in/tumcampusapp/managers/CardManager.java]: Then we probably need a real concurrent data structure. A `ConcurrentSkipListSet` seems to keep the sorting when adding...
