### PR TITLE
Fix ValueRequiredException in startup wizard

### LINKED ISSUE #576: Can't setup tumonline account in startup wizard
## Steps to Reproduce

1. Fresh install
2. Create token and grant all rights in tumonline
3. Click next

## Expected Result

Get to next screen

## Actual Result

Error: Identity could not be accessed. Please check the rights of your TUMonline token

## Problem

I can't get past step 2 in the startup wizard

See [stacktrace.txt](https://github.com/TCA-Team/TumCampusApp/files/1461010/stacktrace.txt)

### Environment
* Phone: HTC 10
* OS version: Android 7.0
* TUM Campus App version: v1.5
* Language: English

screenshot_20171110-112407
screenshot_20171110-112421

### PR DESCRIPTION
**Pull request by anselm92**
Set all obfuscated id fields to not being required to prevent
a VRE in startup wizard when fields bedienstete and extern aren't
set in the response.

Fixes #576

### CODE REVIEW

File: app/src/main/java/de/tum/in/tumcampusapp/models/tumo/ObfuscatedIds.kt [hunk 1]
```diff
@@ -4,6 +4,6 @@ import org.simpleframework.xml.Element
 import org.simpleframework.xml.Root
 
 @Root(name = "row")
```
Comment (kordianbruck) [inline app/src/main/java/de/tum/in/tumcampusapp/models/tumo/ObfuscatedIds.kt]: Why not just use `@Root(strict=false)` instead of adding it to each of the elements?

Comment (anselm92) [reply app/src/main/java/de/tum/in/tumcampusapp/models/tumo/ObfuscatedIds.kt]: This seemed to not have an effect. Exception was still thrown

Comment (kordianbruck) [reply app/src/main/java/de/tum/in/tumcampusapp/models/tumo/ObfuscatedIds.kt]: Wow you are right. https://stackoverflow.com/questions/40487944/parsing-xml-kotlin-android
@pfent this is really dumb.

@anselm92 could you write a unit test for this as well then? Just to make sure this won't break again in the future.

**Comment by anselm92** [comment]
@kordianbruck Jenkins does not run the new test, if i run it locally it is executed though.

**Comment by kordianbruck** [comment]
@anselm92 did you force push or something?

**Comment by anselm92** [comment]
Yes to update my commit

**Comment by kordianbruck** [comment]
@anselm92 any new commit to a branch will automatically update the Pullrequest. No need to force push.
