### PR TITLE
Fix clearing cache makes app unusable

### LINKED ISSUE #636: Clearing the Cache through app makes it unusable
The SQL DB is not recreated by room automatically. Thats why we get multiple exceptions.

Please refine that action, to allow resetting the app without deleting the token.

### PR DESCRIPTION
**Pull request by anselm92**
- Do not drop database tables but instead clear them.
Room can't handle recreation of tables yet and thus trows exceptions
when tables were deleted and not recreated.

Fixes #636

### CODE REVIEW

File: app/src/main/java/de/tum/in/tumcampusapp/managers/AbstractManager.java [hunk 1]
```diff
@@ -64,32 +65,42 @@ public static void resetDb(Context c) {
...
+        tdb.facultyDao().flush();
+        tdb.transportDao().removeCache();
+        tdb.studyRoomDao().removeCache();
+        tdb.studyRoomGroupDao().removeCache();
+        tdb.kinoDao().flush();
+        tdb.widgetsTimetableBlacklistDao().flush();
+        tdb.notificationDao().cleanup();
+        tdb.favoriteDishDao().removeCache();
+        tdb.buildingToGpsDao().removeCache();
+        tdb.wifiMeasurementDao().cleanup();
```
Comment (pfent) [inline app/src/main/java/de/tum/in/tumcampusapp/managers/AbstractManager.java]: We could probably use an Interface for this, but for now it's fine
